In [2]:
import pandas as pd

In [3]:
map = pd.read_csv('/Users/eduardoaraujo/data_sprint_2025/map_regional_health.csv')

map.head()

,macroregion_code,macroregion_name,uf_code,uf,uf_name,macroregional_geocode,macroregional_name,regional_geocode,regional_name,geocode,geocode_name
0,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200013,AC - ACRELANDIA
1,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200054,AC - ASSIS BRASIL
2,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200104,AC - BRASILEIA
3,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200138,AC - BUJARI
4,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200179,AC - CAPIXABA

In [4]:
df = pd.read_csv('/Users/eduardoaraujo/data_sprint_2025/environ_vars.csv.gz')

df = df.merge(map[['geocode', 'regional_geocode']])
df.head()

   geocode  uf_code koppen     biome  regional_geocode
0  1100015       11     Am  Amazônia             11005
1  1100023       11     Am  Amazônia             11001
2  1100031       11     Am  Amazônia             11006
3  1100049       11     Am  Amazônia             11002
4  1100056       11     Am  Amazônia             11006

In [5]:
df.regional_geocode.unique()

array([11005, 11001, 11006, 11002, 11007, 11004, 11003, 12002, 12001,
       12003, 13008, 13009, 13002, 13003, 13001, 13005, 13006, 13007,
       13004, 14001, 14002, 15011, 15003, 15007, 15013, 15001, 15002,
       15012, 15014, 15006, 15009, 15008, 15010, 15004, 16001, 16002,
       16003, 17007, 17002, 17005, 17003, 17006, 17001, 17004, 17008,
       21001, 21005, 21006, 21016, 21002, 21007, 21014, 21003, 21019,
       21008, 21009, 21011, 21004, 21013, 21018, 21015, 21010, 21012,
       21017, 22012, 22004, 22009, 22002, 22006, 22007, 22010, 22011,
       22001, 22003, 22008, 22005, 23023, 23001, 23011, 23024, 23025,
       24004, 24008, 24003, 24006, 24002, 24001, 24005, 24007, 25011,
       25007, 25003, 25002, 25015, 25001, 25009, 25005, 25010, 25006,
       25016, 25014, 25004, 25008, 25013, 25012, 26010, 26001, 26009,
       26003, 26008, 26004, 26005, 26007, 26002, 26011, 26012, 26006,
       27010, 27005, 27007, 27004, 27001, 27008, 27003, 27009, 27006,
       27002, 28007, 28001, 28002, 28003, 28005, 28006, 28004, 29023,
       29017, 29001, 29019, 29025, 29003, 29015, 29026, 29012, 29022,
       29006, 29010, 29028, 29011, 29024, 29002, 29009, 29008, 29018,
       29021, 29007, 29013, 29005, 29014, 29027, 29004, 29016, 29020,
       31074, 31024, 31059, 31060, 31037, 31102, 31072, 31089, 31062,
       31068, 31040, 31008, 31006, 31041, 31001, 31013, 31094, 31036,
       31092, 31095, 31090, 31099, 31035, 31045, 31046, 31064, 31075,
       31061, 31082, 31086, 31070, 31002, 31087, 31044, 31027, 31058,
       31019, 31030, 31021, 31015, 31023, 31097, 31016, 31085, 31017,
       31047, 31011, 31083, 31028, 31034, 31007, 31053, 31051, 31077,
       31101, 31048, 31003, 31055, 31073, 31042, 31010, 31096, 31012,
       31091, 31093, 31067, 31079, 31026, 31066, 31020, 31088, 31071,
       31004, 31052, 31038, 31084, 31065, 31032, 31025, 31078, 31018,
       31050, 31057, 31098, 31100, 31022, 31031, 31009, 31076, 32002,
       32001, 32003, 32004, 33001, 33007, 33002, 33003, 33004, 33005,
       33009, 33008, 33006, 35091, 35156, 35142, 35074, 35061, 35103,
       35062, 35161, 35112, 35051, 35133, 35023, 35163, 35157, 35093,
       35072, 35031, 35104, 35022, 35063, 35172, 35153, 35162, 35021,
       35083, 35101, 35095, 35151, 35011, 35092, 35071, 35155, 35064,
       35121, 35131, 35014, 35052, 35094, 35041, 35033, 35073, 35171,
       35143, 35065, 35012, 35114, 35174, 35173, 35102, 35013, 35132,
       35081, 35032, 35015, 35111, 35154, 35115, 35113, 35082, 35141,
       35152, 35016, 41018, 41002, 41011, 41012, 41014, 41017, 41008,
       41010, 41015, 41001, 41006, 41016, 41003, 41022, 41020, 41019,
       41005, 41007, 41013, 41021, 41004, 41009, 42008, 42003, 42004,
       42002, 42007, 42010, 42001, 42013, 42006, 42011, 42014, 42016,
       42009, 42005, 42017, 42012, 42015, 43022, 43018, 43001, 43013,
       43014, 43003, 43017, 43015, 43019, 43026, 43010, 43021, 43029,
       43009, 43007, 43016, 43004, 43027, 43005, 43008, 43020, 43025,
       43012, 43024, 43030, 43011, 43002, 43006, 43028, 43023, 50013,
       50015, 50017, 50009, 50016, 50014, 50011, 50012, 50010, 51002,
       51006, 51001, 51013, 51009, 51004, 51005, 51011, 51007, 51008,
       51012, 51003, 51014, 51010, 51015, 51016, 52001, 52011, 52015,
       52010, 52003, 52017, 52004, 52014, 52007, 52012, 52009, 52005,
       52002, 52016, 52018, 52008, 52006, 52013, 53001])

In [6]:
df.loc[df.regional_geocode == 31095].biome.value_counts()/df.loc[df.regional_geocode ==31095].shape[0]

biome
Mata Atlântica    1.0
Name: count, dtype: float64

In [7]:
df.groupby('regional_geocode')[['biome']].nunique().biome.value_counts()

biome
1    319
2    119
3      1
Name: count, dtype: int64

In [8]:
biome_counts = df.groupby(['regional_geocode', 'biome'])['geocode'].count().reset_index(name='count')

# Selecionar o bioma com maior contagem em cada regional_geocode
predominant_biome = biome_counts.sort_values('count', ascending=False).drop_duplicates('regional_geocode')

# Resultado final: apenas regional_geocode e bioma predominante
result = predominant_biome[['regional_geocode', 'biome']].reset_index(drop=True)
result['biome'] = result['biome'].replace(
    {'Caatinga':1.0, 'Mata Atlântica':2.0, 'Cerrado':3.0, 'Amazônia':4.0, 'Pampa':5.0,
       'Pantanal':6.0}
)

result

/var/folders/ch/kxpr39wx44v97968yr_4hmch0000gn/T/ipykernel_42178/2156669989.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result['biome'] = result['biome'].replace(

     regional_geocode  biome
0               23011    1.0
1               23023    1.0
2               23001    1.0
3               24006    1.0
4               31007    2.0
..                ...    ...
434             31091    3.0
435             31018    2.0
436             50010    6.0
437             35016    2.0
438             53001    3.0

[439 rows x 2 columns]

In [9]:
result.to_csv('regional_biome.csv.gz', index = False)