In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
df_map = pd.read_csv('/Users/eduardoaraujo/Documents/sprint_data_2025/map_regional_health.csv')

df_map.head()

,macroregion_code,macroregion_name,uf_code,uf,uf_name,macroregional_geocode,macroregional_name,regional_geocode,regional_name,geocode,geocode_name
0,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200013,AC - ACRELANDIA
1,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200054,AC - ASSIS BRASIL
2,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200104,AC - BRASILEIA
3,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200138,AC - BUJARI
4,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200179,AC - CAPIXABA

In [32]:
df_map.groupby(['macroregion_name'])[['regional_geocode']].nunique()

                  regional_geocode
macroregion_name
Centro-Oeste                    44
Nordeste                       117
Norte                           45
Sudeste                        164
Sul                             69

In [6]:
df_pop = pd.read_csv('/Users/eduardoaraujo/Documents/sprint_data_2025/datasus_population_2001_2024.csv.gz')
df_pop = df_pop.loc[df_pop.year==2022]        
df_pop.head()

        geocode  year  population
116970  1100015  2022       23309
116971  1100023  2022      106814
116972  1100031  2022        5836
116973  1100049  2022       95476
116974  1100056  2022       17133

In [25]:
df_agg_pop = df_pop[['geocode', 'population']].merge(df_map[['regional_geocode', 'geocode']])

df_agg_pop = df_agg_pop.groupby(['regional_geocode'])[['population']].sum().reset_index()

df_agg_pop = df_agg_pop.rename(columns = {'population':'pop'})

df_agg_pop = df_agg_pop.merge(df_map[['regional_geocode', 'macroregion_name']].drop_duplicates())

df_agg_pop = df_agg_pop.merge(df_agg_pop.groupby(['macroregion_name'])[['pop']].max().reset_index().rename(columns = {
    'pop': 'pop_max'
}))

df_agg_pop['pop_norm'] =  df_agg_pop['pop']/df_agg_pop['pop_max']

df_agg_pop.head()

   regional_geocode     pop macroregion_name  pop_max  pop_norm
0             11001  236265            Norte  2584129  0.091429
1             11002  182736            Norte  2584129  0.070715
2             11003  355910            Norte  2584129  0.137729
3             11004  611702            Norte  2584129  0.236715
4             11005  138605            Norte  2584129  0.053637

In [26]:
df_agg_pop.shape

(439, 5)

In [27]:
df_agg_pop.pop_norm.max()

np.float64(1.0)

In [28]:
df_agg_pop.to_csv('pop_regional.csv', index = False)