In [1]:
import pandas as pd

In [3]:
df_old = pd.read_csv('dengue.csv.gz')

df_old = df_old.loc[df_old.epiweek < 202501]

df_old.head()

,date,epiweek,geocode,casos,uf,macroregional_geocode,regional_geocode,train_1,target_1,train_2,target_2,train_3,target_3
0,2010-01-03,201001,1100015,3,RO,1101,11005,True,False,True,False,True,False
1,2010-01-03,201001,1100023,12,RO,1102,11001,True,False,True,False,True,False
2,2010-01-03,201001,1100031,2,RO,1101,11006,True,False,True,False,True,False
3,2010-01-03,201001,1100049,159,RO,1101,11002,True,False,True,False,True,False
4,2010-01-03,201001,1100056,9,RO,1101,11006,True,False,True,False,True,False

In [4]:
max(df_old.date)

'2024-12-22'

In [5]:
df_update = pd.read_csv('/Users/eduardoaraujo/Documents/sprint_data_2025/dengue_updated_2025.csv.gz')

df_update.head()

,date,epiweek,casos,geocode,uf,macroregional_geocode,regional_geocode
0,2024-12-29,202501,0,2703601,AL,2704,27002
1,2024-12-29,202501,0,2709400,AL,2704,27004
2,2024-12-29,202501,0,2702553,AL,2703,27008
3,2024-12-29,202501,0,2700607,AL,2704,27001
4,2024-12-29,202501,0,2709152,AL,2704,27005

In [7]:
min(df_update.date)

'2024-12-29'

In [10]:
df_end = pd.concat([df_old[df_update.columns], df_update])

df_end.head()

,date,epiweek,casos,geocode,uf,macroregional_geocode,regional_geocode
0,2010-01-03,201001,3,1100015,RO,1101,11005
1,2010-01-03,201001,12,1100023,RO,1102,11001
2,2010-01-03,201001,2,1100031,RO,1101,11006
3,2010-01-03,201001,159,1100049,RO,1101,11002
4,2010-01-03,201001,9,1100056,RO,1101,11006

In [13]:
min(df_end.date)

'2010-01-03'

In [11]:
max(df_end.date)

'2025-06-15'

In [12]:
df_end.to_csv('dengue_updated.csv.gz')